server:
  port: 9000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.252.131:8848
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

# 服务监控检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
