server:
  port: 9005

spring:
  redis:
    host: 47.100.185.35
    port: 6379
    password: dytqce94lwz
    lettuce:
      pool:
        # 最大活跃连接数，默认是8
        max-active: 100
        # 最大空闲连接数 ，默认是8
        max-idle: 100
        # 最小空闲连接数 ，默认是0
        min-idle: 0

