server:
  port: 9001
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  cloud:
    sentinel:
      transport:
        port: 9001
        dashboard: http://192.168.252.129:8858/
feign:
  sentinel:
    enabled: true

# 服务监控检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
